services:
  web:
    image: archertakesitez/todo-flask-app:latest
    ports:
      - "3000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    volumes:
      - .:/app
    restart: always

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: