apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
spec:
  selector:
    matchLabels:
      app: todo-flask-app
  replicas: 3  # Increase to 3 replicas to better demonstrate rolling updates
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Maximum number of pods that can be unavailable during the update
      maxSurge: 1        # Maximum number of pods that can be created over the desired number
  template:
    metadata:
      labels:
        app: todo-flask-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: todo-flask-app
        image: archertakesitez/todo-flask-app:latest
        command: ["flask"]
        args: ["run", "--host=0.0.0.0", "--port=5000"]
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "development"
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: todo-flask-app
spec:
  selector:
    app: todo-flask-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer  # This exposes the service externally 
